openapi: 3.0.0
info:
  title: Locations
  version: 1.0.0
  description: Locations
paths:
  /v1/api/locations/{id}:
    get:
      summary: Retorna a localização pelo ID
      tags:
        - Locations
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Locations

