openapi: 3.0.0
info:
  title: Locations
  version: 1.0.0
  description: Locations
paths:
  /v1/api/locations:
    post:
      summary: Cria uma nova location
      security:
        - bearerAuth: []
      tags:
        - Locations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Sapu 2
                longitude:
                  type: string
                  example: 12333
                latitude:
                  type: string
                  example: 122332
                municipe_id:
                  type: number
                  example: 1
                description:
                  type: string
                  example: description
      responses:
        200:
          description: localização criada com sucesso
