openapi: 3.0.0
info:
  title: Missing Persons
  version: 1.0.0
  description: Missing Persons
paths:
  /v1/api/missing-persons:
    get:
      summary: Retorna todas as pessoas desaparecidas
      tags:
        - Missing Persons
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Número da página
        - in: query
          name: limit
          schema:
            type: integer
          description: Número de itens por página
      responses:
        200:
          description: Lista de todos as pessoas desaparecidas


