openapi: 3.0.0
info:
  title: Provinces
  version: 1.0.0
  description: Provinces
paths:
  /v1/api/provinces:
    get:
      summary: Retorna todas as provincias
      tags:
        - Provinces
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Número da página
        - in: query
          name: limit
          schema:
            type: integer
          description: Número de itens por página
      responses:
        200:
          description: Lista de provincias
