openapi: 3.0.0
info:
  title: Municipes
  version: 1.0.0
  description: Municipes
paths:
  /v1/api/municipes/search:
    get:
      summary: Pesquisar municipio
      tags:
        - Municipes
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
          description: Nome do municipio para pesquisa
      responses:
        200:
          description: Lista de municipios
        400:
          description: O parâmetro "name" é obrigatório para a busca
